version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Zurich
  open-pull-requests-limit: 20
  assignees:
  - ice987987
  versioning-strategy: increase
