name: Bug report
title: "Bug report"
description: "Create a report to help improve this ioBroker adapter"
labels: needs-triage
body:
  - type: markdown
    attributes:
      value: >
        **Thank you for wanting to report a bug in this adapter!**

        If this is the first time you are doing this, please take a few moments to read
        through the [README](https://github.com/ice987987/ioBroker.husqvarna-automower/blob/main/README.md).

        You are about to report a bug in **"husqvarna-automower"-adapter**. Do not proceed if your issues
        occurs with ioBroker itself, any third party adapters, unofficial or outdated
        adapter versions.

        And finally, make sure any bug you want to report is still present with the **current**
        adapter (beta) version.

        Thank you for your collaboration!
  - type: textarea
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here. Tell us what you were trying to do
        step by step, and what happened that you did not expect.

        Provide a clear and concise description of what the problem is and include as many
        details as possible.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    attributes:
      label: Version of "husqvarna-automower"-adapter
      description: Can be found in the adapters tab of ioBroker admin
    validations:
      required: true
  - type: input
    attributes:
      label: Husqvarna Automower Type
      description: f.ex. 430x
    validations:
      required: true
  - type: input
    attributes:
      label: Version of Node.js
      description: Can be found in the host section of ioBroker admin
    validations:
      required: true
  - type: input
    attributes:
      label: Version of ioBroker js-controller
      description: Can be found in the host section of ioBroker admin
    validations:
      required: true
  - type: input
    attributes:
      label: Version of "admin"-adapter
      description: Can be found in the adapters tab of ioBroker admin
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system incl. version running ioBroker
      description: >-
        Linux (Docker), Windows, MacOS, something else?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Logs and other files needed for analysis
  - type: checkboxes
    attributes:
      label: Checklist of files to include below
      options:
        - label: iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
          required: true
        - label: Contents of the JavaScript browser console (always include in cases of issues with the user interface)
  - type: textarea
    attributes:
      label: Additional information & file uploads
